// The old 2BB blog. Non-episode posts, newest first. Posts with a `body` were transcribed from
// Wayback Machine captures; the rest are title + date only, from the old WordPress feed.
// In a body, a paragraph starting with "> " is a quoted block.
const POSTS = [
  {"date": "Jun 15, 2008", "title": "Happy Father’s Day"},
  {"date": "May 12, 2008", "title": "Our fun-filled Mother’s Day weekend. How was yours?"},
  {"date": "May 8, 2008", "title": "Bump Day. Free ice cream for pregnant peeps."},
  {"date": "Mar 23, 2008", "title": "Audio Comment Line Blues"},
  {"date": "Mar 15, 2008", "title": "We’re still alive"},
  {"date": "Feb 13, 2008", "title": "Podcasters please vote for us boobs and My ooVoo Day is today!"},
  {"date": "Feb 5, 2008", "title": "Join me February 13 at 8pm CST"},
  {"date": "Jan 30, 2008", "title": "How to make a baby pod"},
  {"date": "Dec 21, 2007", "title": "Merry Ho Ho!"},
  {"date": "Nov 29, 2007", "title": "Yo Gabba Gabba! rules."},
  {"date": "Nov 29, 2007", "title": "Happy birthday Heather???"},
  {"date": "Nov 8, 2007", "title": "Message from Sam"},
  {"date": "Oct 25, 2007", "title": "Happy Birthday Sam! Sam turns 2 today. Time sure flies."},
  {"date": "Oct 22, 2007", "title": "iTunes Music Store sends us a birthday email!"},
  {"date": "Oct 15, 2007", "title": "Podcasting for Two Years!"},
  {"date": "Oct 9, 2007", "title": "Happy First Birthday Ella!"},
  {"date": "Oct 8, 2007", "title": "Please vote for us"},
  {"date": "Oct 4, 2007", "title": "Why we removed our Google Adwords"},
  {"date": "Sep 14, 2007", "title": "What we’re up to…"},
  {"date": "Aug 23, 2007", "title": "Sam’s two favorite / favourite songs"},
  {"date": "Aug 23, 2007", "title": "Two Boobs feed"},
  {"date": "Aug 17, 2007", "title": "See you @ BarCamp Nashville tomorrow"},
  {"date": "Aug 7, 2007", "title": "WordPress is updated"},
  {"date": "Aug 6, 2007", "title": "Updating the blog"},
  {"date": "Jul 16, 2007", "title": "Urban Baby Runway discount", "body": ["Hey gang:", "A while back we had a contest with Urban Baby Runway. They are super cool people who happen to sell super cool things. I recommend you drop by and check out their children’s clothing and accessories.", "On that note, Cara, was kind enough to send us a custom made Two Boobs and a Baby + t-shirt for Sam and for Ella. How cool is that? See, I told you - super cool.", "If you like what you see on their site www.urbanbabyrunway.com you can use the code: UBR2B to save 15%!", "Thanks again Cara. We love Urban Baby Runway.", "Details on the winners of the (very extended) Daddy Needs a Drink Contest very soon.", "Cheers,\nDave"]},
  {"date": "Jul 10, 2007", "title": "Nanny snatching", "body": ["Tim from the Twisted Wrist podcast sent this article today. It’s scary what people are doing to get decent nannies. This Globe article is about Nanny snatchers, it’s worth the read.", "A friend I worked with gave me some advice about parenting way back before Sam was born. He said to never tell anyone about your babysitter. His advice is really solid, because often times you’ll find you go out for dinner with friends who live in your neighbourhood. This means that they will be looking for a sitter too. Think about it.", "Have you ever had your nanny or sitter stolen from you?", "Dave"]},
  {"date": "Jun 27, 2007", "title": "Thoughts on Podcasters Across Borders", "body": ["As you guys all know, I just got back from Podcasters Across Borders on Sunday night. I am in the middle of planning a similar tech conference called BarCamp Nashville. Drop by the blog to read my thoughts about PAB2007.", "I recorded a little something for you which I hope to have up shortly, stay subscribed.", "Cheers,\nDave"]},
  {"date": "Jun 19, 2007", "title": "The un-official Podcasters Across Borders Meme", "body": ["I’ll be heading to Kingston, Ontario for Podcasters Across Borders and to hook up with my Canadian (and international) podcasting brothers and sisters this weekend. Here’s the un-official Podcasters Across Borders Meme (created by Sean McGaughey):", "Why are you coming to PAB?\nI am really looking forward to seeing old friends from the Canadian podcasting community, plus make new international ones. Oh, and to drink beer.", "A little homework now: Which PAB registrants would you like to meet? Why?\nI would love to meet Chris Brogan, I really enjoy his blog and think he’s doing some fantastic work engaging his audience. I also really want to speak with Ken, AKA the Scarborough Dude. We didn’t get nearly enough time to chat and drink together last year. I am a long time listener of Dicks N’ Janes. Plus I want to meet YOU!", "Who is your “dream interview” for your podcast? Why?\nDream interview? We have a parenting podcast called Two Boobs and a Baby +. I’m not really sure who would be a dream interview, perhaps our future grandchildren. That would be cool.", "Who would you like to interview at podcamp Podcasters Across Borders?\nI have no plans to interview anyone at PAB.", "What is your, “Can’t miss it” session at podcamp Podcasters Across Borders?\nManaging Your Social Media by Bryan Person. I’m a big fan of Bryper’, plus I live and breath social media.", "What is your favorite podcast?\nToo many to name, here’s a few: Six Pixels of Separation, In Over Your Head, Canadian Podcast Buffet, The Sniffer, NewComm Road, Managing the Gray, Dicks N’ Janes, NPR All Songs Considered, CBC Best of the Current...", "What is your favorite web resource?\nJott.com", "Who is your favorite podsafe musician? (eg. Sean McGaughey).\nUncle Seth", "Ginger or Maryanne?\nDoes Gingeranne count? When I was little it was Ginger, but I’ve matured into a Maryanne man now.", "Bob, Mark, or Tod?\nDoes BobMarkTod count? When I was little it was Bob, but I’ve matured into a Mark man now. Sorry Tod, see you in Hamilton."]},
  {"date": "Jun 19, 2007", "title": "Our wedding cake, six years later", "body": ["In all of the chaos over the last few weeks/months we have failed to mention a very special day that past last weekend. Yes, Father’s Day is an important one (Happy belated Dad’s day folks), but that’s not the day I’m talking about.", "On Saturday, June 16, Heather and I “celebrated” our sixth year anniversary. I quoted the word celebrated because we painted and moved in all weekend (and we’re still doing this). Hardly a celebration, but we’ll treat ourselves to a nice dinner somewhere soon enough.", "You’ll find a great snapshot of Heather and I discovering our frozen wedding cake in her parent’s deep freezer which they gave us. We were moving it in to the garage from the Uhaul when we cracked it open to find an odd shaped, tin foil covered dish. You’re suppose to wait one year, then eat some of your wedding cake for good luck. We waited six years and decided to pass on eating some. Oh, those red nasty things are/were rose pedals.", "A new episode will be available soon. I can’t promise you when, but I can tell you that our contest is in fact still open!"]},
  {"date": "Jun 15, 2007", "title": "Our new house", "body": ["Hey folks:", "We are doing our best to get a new episode out to you, and to pick some winners (five of you) for the Daddy Needs a Drink Contest. If you haven’t already entered you’re in luck. We’re going to keep it open until we actually produce the episode, which will likely be next week now. Things are simply too crazy right now.", "Moving into a house with two kids under two is insane!", "Cheers,\nDave"]},
  {"date": "Jun 14, 2007", "title": "A woman was almost arrested over her 19 month son’s sippy cup at customs.", "body": ["Don’t even get me started about customs. I’ve had my own horror stories as you all know.", "> TSA detains woman over infant’s sippy cup — I feel safer!\nJordan says: “This one just made my blood boil: a mom was bullied by a gaggle of security officers at Dulles Airport in Washington, D.C. over the water in her 19-month-old son’s sippy cup. The story starts out sort of funny, with the sippy cup being seen as some sort of deadly weapon, but quickly spirals into nightmare territory. This is a national embarassment; I feel more threatened by these uniformed goons than I do by terrorists, and I lived in NYC during 9/11.”"]},
  {"date": "Jun 14, 2007", "title": "Expecting Dads expect to suffer too…", "body": ["There’s am interesting article on Slate today about new findings on how expecting fathers suffer many of the same symptoms as expecting mothers. I know I suffered along with Heather as we consumed copious amounts of Ed’s homemade ice cream."]},
  {"date": "Jun 11, 2007", "title": "Contest extention", "body": ["Hey gang:", "I just wanted to write briefly to let you know that the “Daddy Needs a Drink” Contest has been extended until this Thursday @ noon. Yes, we said we were going to do a new episode yesterday (Sunday), but due to unforeseen issues we want to extend the deadline.", "I’m still trying to get to the bottom of our iTunes feed issue, it seems to be working now. We’re extending the contest to be fair to everyone, because many of you who subscribe to the show using iTunes had no idea there was a new episode, let alone a contest.", "The good news: You all get a chance to win one of five copies of Robert Wilder’s “Daddy Needs a Drink”.", "The bad news: Winners will not receive their prize until after Father’s Day. Sorry about that, but it’s free and free ain’t bad.", "Cheers,\nDave"]},
  {"date": "Jun 3, 2007", "title": "Daddy Needs a Drink Contest tomorrow"},
  {"date": "May 29, 2007", "title": "BarCamp Nashville"},
  {"date": "May 25, 2007", "title": "Update"},
  {"date": "May 13, 2007", "title": "Happy Mother’s Day everyone!"},
  {"date": "May 9, 2007", "title": "Two Boobs and a Baby FACEBOOK group"},
  {"date": "May 8, 2007", "title": "Happy Birthday Heather!"},
  {"date": "May 1, 2007", "title": "Momo’s visit, green cards, house hunting"},
  {"date": "Apr 25, 2007", "title": "New Audio Comment Line Number: 206-350-4819"},
  {"date": "Apr 24, 2007", "title": "Good morning Jackson"},
  {"date": "Apr 22, 2007", "title": "Lots of firsts"},
  {"date": "Apr 10, 2007", "title": "Easter Bunny"},
  {"date": "Apr 10, 2007", "title": "Pimp My Stroller"},
  {"date": "Apr 7, 2007", "title": "Classic Sesame Street - Cookie Computer Song"},
  {"date": "Apr 6, 2007", "title": "We’re sorry…so sorry"},
  {"date": "Apr 3, 2007", "title": "Is your browser up to date?"},
  {"date": "Mar 31, 2007", "title": "Upgrading Forum"},
  {"date": "Mar 20, 2007", "title": "Another baby is born, an ear infection (again) and Facebook"},
  {"date": "Mar 13, 2007", "title": "Sam’s First Haircut"},
  {"date": "Mar 12, 2007", "title": "Ella’s Five Month Check Up"},
  {"date": "Mar 7, 2007", "title": "New photos of Ella & Sam"},
  {"date": "Mar 6, 2007", "title": "We’re in the March issue of Podcast User Magazine"},
  {"date": "Mar 6, 2007", "title": "No Fifth’s for us"},
  {"date": "Mar 6, 2007", "title": "Fifth’s Disease"},
  {"date": "Mar 4, 2007", "title": "Cookies, coffee and crupe?"},
  {"date": "Feb 27, 2007", "title": "Sick update"},
  {"date": "Feb 24, 2007", "title": "Our first video"},
  {"date": "Feb 23, 2007", "title": "Sick Day(s)"},
  {"date": "Feb 15, 2007", "title": "We’re featured in iTunes Music Store"},
  {"date": "Feb 11, 2007", "title": "Last call for our Alternadad contest"},
  {"date": "Feb 10, 2007", "title": "The Official Two Boobs and a Baby + Email Newsletter"},
  {"date": "Feb 9, 2007", "title": "Montreal bloggers rock! US consulates - not so much"},
  {"date": "Jan 30, 2007", "title": "New Audio Comment Number 206-337-1257", "body": ["Hi there:", "Thanks for dropping by the site. Our previous audio comment number is now defunct. It appears that we need one voice message per 30 days, or the number goes dead.", "On that note...please please please give us a call. We really want to hear from you.", "Please tell us:\n* What you think about the show.\n* Tips on improving the show.\n* Your family stories.\n* Your product and service reviews.\n* Anything relating to a recent episode.\n* Or just call us to say hello.", "What are you waiting for? Call 206-337-1257 and leave a message at the beep. Easy.", "We’re looking forward to hearing from you.", "Cheers,\nDave & Heather"]},
  {"date": "Jan 21, 2007", "title": "Sick Boob", "body": ["Heather’s sick. We’ve been trying to get out a new episode, but she’s been under the weather. It’s weird too. She woke up a few days ago with a fever and vomiting. She spent a day down, then the next day she felt much better, not 100%, but better.", "This morning she awoke with a fever and vomiting again. She’s starting to feel better now, since she spent the day in bed again. Poor thing.", "We hope to have a new episode to you tomorrow. Stay tuned.", "In the mean time, please feel free to drop by my new blog: New Media Nashville.", "Cheers,\nDave"]},
  {"date": "Jan 18, 2007", "title": "Podcast Peer Awards", "body": ["Hey gang. Many of our listeners are fellow podcasters. We’re always thrilled to hear from everyone who tunes in to the boobs each week.", "If you happen to be a podcaster, and you dig what we’re doing, I’m asking for a favour.", "Please take a moment to vote for us on the annual Podcast Peer Awards.", "You follow this link to the Parenting section. You’ll need to register (for free) to cast your vote.", "Hey. Thanks a million!\nDave & Heather", "PS: New episode very soon. Stay tuned/subscribed."]},
  {"date": "Jan 7, 2007", "title": "Live from Tennessee", "body": ["Thank god I made it across the border. I was so nervous meeting the US customs guy. I felt like the dude in Midnight Express (except I didn’t have pounds of hash taped to my chest).", "I am now reunited with my family, which means we’ll have a new episode out to you very soon.", "Stay tuned."]},
  {"date": "Jan 4, 2007", "title": "Guest Book", "body": ["There’s been a bunch of great posts in our Guest Book recently. I think some times people miss checking it out. I should also mention that we always see the posts, but we can’t comment or reply to them, because that’s how the page is set up.", "On that note, I thought I would share some new posts here. You can always visit the Guest Book to read other people’s posts, or to leave your own.", "Cheers,\nDave", "> Hello Delaney’s\nI found your podcast about 2 weeks ago and have been listening everyday at work. I’m up to episode 25 so I am almost caught up. I love the podcast. I can’t wait until I am caught up so I can email you comments that are not months behind.\nHave a great day,\nChayse (mom of 2, 6&8)", "Thanks for your post Chayse. Welcome to the show! Please feel free to post your comments after the episodes listed on the blog or in the forum. We love to hear your feedback.", "Happy New Year,\nDave & Heather", "> Hello,\nWe are 17weeks on our first child and I am on your 4th pod cast. You guys are fun!\nThanks for the pod casts!!\nTed and Jen", "Merci Ted and Jen. 17 weeks! Wow, congratulations. Ella will be 12 weeks this Monday and Sam will be 15 weeks. So, I understand how hectic life can get.", "Have a happy healthy New Year.\nDave & Heather", "> Hi there\nI found your podcast only a couple of days ago. It’s really to bad I didn’t know about it when you started, because my daughter Rana was born only a month before Sam. It would have been so much fun (and so reassuring) to hear you make the same observations and wonder about the same confusing things as we did at that time. But well, I got my iPod only 3 or so weeks ago and didn’t really know about podcasts before ... So, I’m catching up, enjoying it very much.\nYou’re doing a great job. I really enjoy your show - and Heather’s laughing. You got a beautiful laughter\nGreetings from Europe,\nTina", "Heather says thanks for the laughter comment Tina. Congrats on your baby too, I’m sure Rana must be all over the place now, Sam sure is!", "Part of the reason we do this podcast is to help new parents. Parenting and pregnancy sure isn’t easy, but it’s got the best results you could ever hope for.", "It’s hard to imagine Heather and I without Ella and Sam (but if you MUST know, check out Episode 1 and 2).", "All the best.\nHappy New Year.\nDave & Heather"]},
  {"date": "Jan 2, 2007", "title": "We had twins and triplets in the space of a year", "body": ["Oh my. And I thought having two kids in 11.5 months was hard...", "Check out this story of a woman in the U.K. who had five kids in one year!", "Happy New Year lady! Good luck."]},
  {"date": "Jan 2, 2007", "title": "My new years resolution…", "body": ["My new years resolution is to tell more people about our podcast. Yours should be the same, what do you think? Sound like a plan? How about it then? Are ya game?", "I just realized iTunes let’s you tell a friend. Just follow this link.", "Then send the card to a friend to let them know all about the show.", "If you do this you rock and we love you!", "Happy 2007. Dave."]},
  {"date": "Jan 1, 2007", "title": "Happy New Year!"},
  {"date": "Dec 29, 2006", "title": "Crappy New Year"},
  {"date": "Dec 19, 2006", "title": "Less than 12 days until Christmas!"},
  {"date": "Nov 21, 2006", "title": "Ella’s birth announcement"},
  {"date": "Nov 21, 2006", "title": "What’s new Boobs?"},
  {"date": "Oct 31, 2006", "title": "Happy Halloween"},
  {"date": "Oct 24, 2006", "title": "Happy First Birthday Sam!"},
  {"date": "Oct 16, 2006", "title": "One year anniversary of Two Boobs and a Baby!"},
  {"date": "Oct 11, 2006", "title": "Weight pool"},
  {"date": "Oct 10, 2006", "title": "Introducing Ella: Ella is born!"},
  {"date": "Oct 7, 2006", "title": "Happy First Birthday Sam!"},
  {"date": "Sep 22, 2006", "title": "Salmonella", "body": ["Here’s a message that was posted in our guestbook in case you missed it...", "> Posted by Kate, London, UK - 09/20/2006\nHi Dave and Heather,\nJust found your podcast and really enjoying it. Bizarre coincidence though - was listening on the tube this morning, and as Dave said he used to live in Willesden Green in London, my train was just pulling out on the way to Kilburn. Bizarre.\nOne question - are Sam and Ella really your kids (and unborn kids’!) names? Did no-one ever suggest that this sounded like salmonella? Am kind of hoping that this is how you’re anonymising them, since although I love the names separately, I’m not keen on them together!\nThat said, keep up the good work (and good luck Heather!)", "We’ve talked about this on a passed episode and in the forum a bit, but I thought I would share the story behind their names.", "When we first got pregnant, we were sure we were having a girl. Heather has two sisters and no brothers, and her family have a lot of women, so it just made sense. So we moved ahead through the pregnancy, always thinking we had a wee lassie in Heather’s tummy. After careful consideration, we decided that Ella would be the best name - and so it was.", "During the ultrasound, the technician pointed out Ella’s penis! But! What? We were flabbergasted. A boy? How could this be? The more we thought about it, the more excited we were about the thought of having a son. Lots of names were mentioned, but the only one that stuck was Sam.", "You see, Heather’s dad’s name is Sam too. Since all three of his daughters have married, his family surname is no more, because his daughters chose their husband’s surname. It was this thinking and the fact that Sam is such a cool name, that we settled on it - and so IT was.", "As you all know, our big announcement about 9 months ago, was that we were pregnant again. The process of choosing a name was tough, until we found out that we were having a girl this time. Straight away we thought of Ella again. Then we said the two names in a single breath “Sam and Ella”. Yikes.", "One of our loyal listeners, Expatcdn, posted a message in our forum about her concerns with our choice in names. Ginafish mentioned it being a fun one to yell at the park too!", "Long story short, Ella is perfect for her, no other name would do.", "We figure having a grill out/bbq and asking for donations for “Sam ‘n Ella” funding would be fine. What do you guys think?", "Cheers.\nDave"]},
  {"date": "Sep 11, 2006", "title": "Episode 26 almost ready"},
  {"date": "Aug 23, 2006", "title": "2BB Update"},
  {"date": "Aug 3, 2006", "title": "Postcard", "body": ["We’re having a blast in Tennessee. Wish ya’ll were here with us. We’re going to record a new episode soon; I hope to get it up and out to you ASAP.", "Stay tuned!", "Oh, and Squeet isn’t working for some reason. So if you have signed up for email notifications, please do so again.", "Cheers,\nDave"]},
  {"date": "Jul 22, 2006", "title": "Welcome Beach Buddies", "body": ["We just did a bit of postering to promote our show in the Beach in Toronto. Welcome if you found our flyer and are visiting for the first time.", "This podcast is all about being a first time parent. As our regular listeners will tell you, the show is hosted by a couple of boobs - we’re the real thing! We have no idea! Ha!", "Sit back and download an archived episode. Or tune into the latest one, by pressing the “Listen Now” button above this post, or the play button here.", "If you like what you hear, please let us know. You can also subscribe for free in iTunes be simply visiting this link.", "Well that’s all for now. Enjoy the show!", "Cheers,\nDave & Heather"]},
  {"date": "Jul 20, 2006", "title": "Did you get an error page first?", "body": ["Howdy.", "I’m trying to gauge how serious (if at all) our database issue is. It seems that some times visitors can’t access www.twoboobsandababy.com and instead get a WordPress error page.", "Can you please let me know if this is happening (yes or no). I have set up a POLL at the bottom of the page. Please scroll down and choose.", "If this is happening to you please give it a minute, then refresh your browser - it should reload within a minute or so.", "Thanks for your patience. This will be resolved very soon.", "Cheers,\nDave"]},
  {"date": "Jul 17, 2006", "title": "Sleep...must have sleep", "body": ["Well folks, I must apologize for not having a new episode out quite yet. As you heard in Episode 21, Sam has not been the easiest sleeper lately.", "The last couple of nights have left Heather and I absolutely exhausted. After an hour of trying to get him down, exiting the room and reentering to put him down again...well it hasn’t been easy.", "I swear it’s as if he’s addicted to the crib gate. He must have them in his hands, so that he can raise himself up to his knees, then to his feet. Once up, he gleefully bounces back and forth hanging on to the top of the gate. Don’t worry, he’s still at a safe height so not to fall over the gate.", "Anyhoo...Heather and Sam are heading back to Tennessee for the next 3 weeks on Wednesday. I’ll be heading for 10 days during that time too, so I won’t be alone too long.", "I’ll be attempting to do Episode 23 with Heather via Skype (over the phone), we’ll see how it goes.", "It’s such a funny thing, because I long for a little peace, but I know once he’s gone (and his mum of course), I’m going to miss him like crazy (and his mum).", "Episode 22 coming tomorrow.", "This is your last chance to leave us an audio comment to include in tomorrows show. Let us know what’s on your mind! If you’d just like to say hello, we’d love to hear from you.", "Cheers,\nDave"]},
  {"date": "Jul 13, 2006", "title": "2 days remain! We need your vote!", "body": ["Hi there:", "This is our last annoying message to PLEASE ask for your support. It will just take you one minute to visit the link below, and enter Two Boobs and a Baby under PEOPLES CHOICE and/or COMEDY.", "We hope to see your support!", "Thanks!\nDave, Heather, Sam, and Ella (in the bella!)"]},
  {"date": "Jul 3, 2006", "title": "Podcast Awards", "body": ["Hi there: We figure you’re here because you like our show, or you’re just checking out Two Boobs and a Baby for the first time. Either way, if you enjoy our podcast, we’d appreciate your nomination for the Podcast Awards. We think the two most suitable categories are: PEOPLES CHOICE and/or COMEDY.", "Hope to see your support!", "Thanks!"]},
  {"date": "Apr 3, 2006", "title": "Ride for Heart", "body": ["Hi everyone:", "I am participating in the Canadian Heart & Stroke Foundation RIDE FOR HEART. It’s a 25 kilometre bike ride across Toronto on June 5th. I really need your pledges to help support the cause.", "Please visit RIDE FOR HEART to make your pledge. Enter my name to donate. All proceeds go to the Heart and Stroke Foundation. It’s a great cause!", "I hope to see your support. Thanks very much.", "Dave"]},
  {"date": "Apr 2, 2006", "title": "Greetings from Atlanta", "body": ["I just got back this afternoon from Atlanta. As we mentioned in our last episode, Heather and I met in Georgia for a friend’s wedding. Heather has been home in Tennessee with Sam for the last week. The plan was for her to leave Sam with her folks, while she came to Atlanta to meet me for the weekend. After the wedding, Heather drove back to her parents place, to stay for another couple of days. My family returns Tuesday, and I can’t wait!", "It was nice to get away from home for a short break, plus have Heather to myself for a weekend...but I MISS SAM!!!", "I must say that Atlanta is one cool city. I didn’t really know what to expect. Peaches and Olympics was all I could think of...oh and when the Toronto Blue Jays beat the Atlanta Braves for the World Series in the 90’s.", "We found a couple of restaurants worth mentioning to all ya’ll! These all get the Two Boobs seal of approal!", "First: The Silver Skillet. Talk about your typical southern diner. The servings were large and the service was sweet. The walls were littered with funny, old signs, and the booths were just tight enough.", "Second: Fat Matt’s. If you’re looking for a rockin’, live Rythym and Blues, rib and chicken joint...this place is for you. Need I say more?", "We also stumbled upon a tres hip community called Little Five Points. We felt right at home, surrounded by college kids, punk rock record shops, skate shops, and a massive beer garden/bar called The Brewhouse Cafe. This neighbourhood is definitely worth checking out. It is similar to the Camden Market in London, and Kensington Market in Toronto.", "As for Episode 12 and your promised BIG SURPRISE....stay tuned!", "Cheers.\nDave"]},
  {"date": "Mar 21, 2006", "title": "Want to Win a FREE FREAKIN’ iPOD NANO?", "body": ["Want to win one of these?", "Here’s a very easy way to enter to win an Apple iPod nano. Simply visit: www.openyourears.ca and take the quick and easy four sevens survey.", "The winner of the iPod nano will be announced at the end of April, so you’ve got plenty of time to fill in the blanks. Good luck!", "If you win one, we win one too...now how’s that for a sweet deal?", "Don’t forget to tell your friends!"]},
  {"date": "Mar 16, 2006", "title": "Happy Paddy’s Day", "body": ["It’s 8:35pm on the eve of St. Patrick’s Day. Friends are congregating in their usual watering holes tomorrow to celebrate the best day of the year to get pie-eyed. As the luck of the Irish would have it, this year Paddy’s Day is on a Friday, so the fortunate folks will be able to spend Saturday in bed recovering (or picking up where they left off the night before).", "The thought of downing a “few” pints of Guinness is killing me as I type this. As I held Sam in my arms tonight feeding him his own bottle (formula, not Guinness), I got to thinking about the significance of Paddy’s Day.", "I would lie if I said that I didn’t want to be out with Heather, my brother Mike, and our friends on this, the one day of the year that alcoholism is applauded. As I fed Sam, I starting thinking about Ireland, about Galway, and about how Heather and I met, and our history together in Ireland and where the journey has taken us.", "I have to say that even though I’m Canadian, I certainly have had a lot of luck (perhaps of the Irish). Leaving Canada in 1998 to move to Ireland was the best move of my life. It was filled with hardship, poverty, a steady diet of beer and curry chips, screaming fiddles, and bellowing young drunken Paddy’s singing “The Fields of Athenry” on the streets below my window during the wee hours.", "This year I won’t be painting my head tri-coloured, or even green for that matter. I won’t be heading to the pubs, because I have the responsibility of being home with Sam and Heather. We’ll be sober; perhaps I’ll sneak in a pint or two though. Our friends will be out downing creamy pints, and listening to the best traditional players Toronto has to offer.", "I can honestly say that I don’t care. Moving to Ireland was the best move I’ve ever made, because I met Heather there, the best thing that’s ever happened to me. Now we have our son Sam, who is the most incredible addition to our family we could have dreamed of.", "In years to come I’ll be sure to take Sam out to hear sessions, and to visit Ireland, and Galway where it all began. He’ll meet our good friends there, down pints of Guinness with us all. We’ll share in stories and be sure to enjoy the craic that brought us together in the first place.", "Happy St. Patrick’s Day."]},
  {"date": "Mar 13, 2006", "title": "We want you!", "body": ["As you probably know, we’re still learning how to be parents. This is an ever evolving job, but we’re loving every minute of it.", "We are looking for your insight in the questions we raise during our shows, but also in anything you can think of. Many of our listeners are new parents too.", "If you share your stories, tips and tricks, we can help one another through this incredible journey.", "Only you can make the forum a great source of information and fun. Why not stop in and introduce yourself? You never know who you’re going to meet.", "On that note..please visit the Two Boobs and a Baby Forum now.", "We hope to see you inside."]},
  {"date": "Mar 10, 2006", "title": "Hear our Promo", "body": ["Hi everyone:", "Heather and I produced a short promo for our show. You can hear it on Canadian Podcast Buffet today, or on Podfinder.", "Thanks Mark, Bob and Adam!", "Cheers,\nDave"]},
  {"date": "Mar 7, 2006", "title": "Frappr World Map", "body": ["Have you joined our Frappr Map yet? It’s really easy.", "Just click the map, then tell us where you’re at! Done. Easy right?", "My little IP counter tells me that one of you who tuned in today is from the Faroe Islands...but you have not joined our map yet? Oh come on...please...we’re dying to see how many listeners we have in the Faroe Islands.", "Do it...come on...ya know ya wanna..."]}
];

// A few threads from the old forum: [topic, [[author, date, text], ...]]
const THREADS = [
  ["Are you a fetus?", [["dave", "Aug 26, 2006", "I am in the middle of setting up automatic notifications, so you can receive an email when there is a reply to your posts.\nFor some fun, I also added some forum rankings. If you post a certain number of messages, your ranking status changes.\nFor example: If you post 0 messages, you’re considered a fetus. 5 messages, you’re a new born, etc.\nFetus 0 · New Born 5 · Infant 10 · Toddler 20 · Kiddo 30 · Teenager 50\nWhat are you?"], ["Carly D.", "Aug 26, 2006", "I’m just a fetus!\nHmmm...guess I better start posting more."], ["dave", "Aug 26, 2006", "Get posting Carly. Ha!"], ["Carly D.", "Aug 26, 2006", "oh i will i will"], ["im the mommy thats why", "Oct 5, 2006", "fetus,\nbut a big one!"], ["Ginafish", "Oct 16, 2006", "What am I? A fetus? Well, we’ll just have to see about fixing that won’t we? :)"], ["dave", "Oct 17, 2006", "You’re already a toddler!\nHow quickly they grow...sigh.\nDave"]]],
  ["Is it a boy or is it a girl?", [["dave", "May 15, 2006", "Tell us your guess here!\nWe’ll let you know THIS Wednesday.\nCheers,\nDave & Heather"], ["Neasa", "May 16, 2006", "I think it’ll be a girl but now that I’ve said a girl, it’ll probably be a boy or maybe a girl or maybe it is a boy. No I’ve sticking my neck out here - a fiver at even odds it’s a girl!"], ["LoopyNZ", "May 16, 2006", "I consulted the oracle (flipped a coin) and it’s definitely a girl!\n- Loopy (also definitely a girl) -"], ["Ginafish", "May 16, 2006", "I’m going to guess it’s a baby! No... wait... a turnip? Nah, definitely a baby. And I’m going to guess that it’s another boy. Hmmmm..."], ["LoopyNZ", "May 19, 2006", "Hi Dave and Heather,\nI just listened to Episode 16 (and I had the self-control not to skip to the end to find out your news).\nCONGRATULATIONS!!!\nNow you guys get to go on a crazy shopping spree for pink stuff! In theory I’m not keen on lots pink, but I know as soon as I have a little girl I won’t be able to resist.\n- Loopy -"]]],
  ["One a week...one a week...one a...", [["dave", "Feb 7, 2006", "Yes, so you’ve all been routing for us to do one episode a week. We really appreciate all of your support in pushing us to do: one a week, one a week, one a week...\nUnfortunately, with Heather and Sam in Arizona this weekend, and me in New York...well...we’re going to be running a little late.\nWe’ll shoot for mid-week next week to fill you in with all of the juicy gossip from our travels.\nMy brother will be here house sitting - no wild parties!\nCheers kids!\nDave, Heather and Sam."], ["im the mommy thats why", "Oct 5, 2006", "you’ll be lucky to get one in one a month as the kids get older! Or at least I would be! But I know I would love to hear you guys once a week!"], ["dave", "Oct 5, 2006", "Thanks. We’ll do our best to keep it up. We may have to start shooting for a bit of a shorter show going forward, but we’ll just have to see how things go...\nDon’t forget to subscribe, so you’ll get automatic updates when new episodes are available.\nYou can do this by using our iTunes button on the main page, or by entering your email address on the main page for automated updates.\nCheers!\nDave"]]]
];

const esc = s => String(s ?? "").replace(/&/g, "&amp;").replace(/</g, "&lt;").replace(/"/g, "&quot;");
const para = t => t.startsWith("> ")
  ? `<blockquote>${esc(t.slice(2))}</blockquote>`
  : `<p>${esc(t)}</p>`;

const list = document.getElementById("blog-list");
let year = "";
list.innerHTML = POSTS.map(p => {
  const y = p.date.slice(-4);
  const head = y !== year ? `<h2 class="blog-year">${year = y}</h2>` : "";
  return head + (p.body
    ? `<article class="extra post"><div class="extra-head"><h3 class="extra-title">${esc(p.title)}</h3><span class="extra-date">${esc(p.date)}</span></div><div class="post-body">${p.body.map(para).join("")}</div></article>`
    : `<div class="post-slim"><span class="extra-date">${esc(p.date)}</span><span class="post-slim-title">${esc(p.title)}</span></div>`);
}).join("");
document.getElementById("blog-count").textContent = `${POSTS.length} posts`;

document.getElementById("forum-list").innerHTML = THREADS.map(([topic, msgs]) => `
  <article class="extra thread"><div class="extra-head"><span class="extra-type">FORUM</span><h3 class="extra-title">${esc(topic)}</h3></div>
  ${msgs.map(([who, when, text]) => `<div class="msg"><div class="msg-who"><strong>${esc(who)}</strong> <span class="extra-date">${esc(when)}</span></div><p>${esc(text)}</p></div>`).join("")}
  </article>`).join("");
