// Episodes load live from the Internet Archive item below and play with Plyr.
const ARCHIVE_ITEM = "2-bb-50";

// Release years from each MP3's original ID3 tag. 23 and 42–44 are inferred from neighbouring episodes.
const YEARS = {
  "2BB1":2005,"2BB2":2005,"2BB3":2005,"2BB4":2005,
  "2BB5":2006,"2BB6":2006,"2BB7":2006,"2BB8":2006,"2BB9":2006,"2BB10":2006,"2BB11":2006,"2BB12":2006,"2BB13":2006,
  "2BB14":2006,"2BB15":2006,"2BB16":2006,"2BB17":2006,"2BB18":2006,"2BB19":2006,"2BB20":2006,"2BB21":2006,"2BB22":2006,
  "2BB23":2006,"2BB24":2006,"2BB25":2006,"2BB26":2006,"2BB27":2006,"2BB28":2006,"2BB29":2006,"2BB30":2006,"2BB31":2006,"2BB32":2006,
  "2BB33":2007,"2BB34":2007,"2BB35":2007,"2BB36":2007,"2BB37":2007,"2BB38a":2007,"2BB38b":2007,"2BB39":2007,"2BB40":2007,
  "2BB41":2007,"2BB42":2007,"2BB43":2007,"2BB44":2007,"2BB45":2007,
  "2BB49":2008,"2BB50":2008
};

// Full release dates and show notes. Episodes 1–21 come from the podcast.net directory listing (Jul 2006 capture);
// episode 5 and episodes 22–48 come from the old WordPress feed (Jun 2008), with feed times converted from GMT
// to local time (Toronto through 2006, Tennessee from 2007). Where a capture of the old blog shows the post
// date (episodes 9, 11, 21–23), that date is used. Treat the rest as accurate to within a day or so. Episode 38's entry is the "V.2.0" post.
const DATES = {
  "2BB1":"Oct 16, 2005","2BB2":"Oct 25, 2005","2BB3":"Dec 1, 2005","2BB4":"Dec 24, 2005","2BB5":"Jan 2006",
  "2BB6":"Feb 5, 2006","2BB7":"Feb 20, 2006","2BB8":"Feb 28, 2006","2BB9":"Mar 8, 2006","2BB10":"Mar 21, 2006",
  "2BB11":"Mar 26, 2006","2BB12":"Apr 10, 2006","2BB13":"Apr 24, 2006","2BB14":"May 2, 2006","2BB15":"May 9, 2006",
  "2BB16":"May 18, 2006","2BB17":"Jun 1, 2006","2BB18":"Jun 9, 2006","2BB19":"Jun 29, 2006","2BB20":"Jul 2, 2006",
  "2BB21":"Jul 10, 2006","2BB22":"Jul 18, 2006","2BB23":"Jul 26, 2006","2BB24":"Aug 27, 2006","2BB25":"Sep 4, 2006",
  "2BB26":"Sep 19, 2006","2BB27":"Oct 2, 2006","2BB28":"Oct 12, 2006","2BB29":"Nov 3, 2006","2BB30":"Nov 13, 2006",
  "2BB31":"Dec 9, 2006","2BB32":"Dec 24, 2006","2BB33":"Jan 12, 2007","2BB34":"Jan 24, 2007","2BB35":"Feb 2, 2007",
  "2BB36":"Feb 14, 2007","2BB37":"Mar 6, 2007","2BB38a":"Mar 15, 2007","2BB38b":"Mar 15, 2007","2BB39":"Mar 21, 2007",
  "2BB40":"Apr 11, 2007","2BB41":"Apr 25, 2007","2BB42":"May 15, 2007","2BB43":"Jun 5, 2007","2BB44":"Aug 5, 2007",
  "2BB45":"Sep 24, 2007","2BB46":"Nov 6, 2007","2BB47":"Jan 18, 2008","2BB48":"Mar 23, 2008","2BB49":"Jun 19, 2008"
};
// The last two files in the archive.org item are numbered one and two behind the episodes they hold: 2BB49.mp3 is
// episode 50 ("From the Deck on Father's Day") and 2BB50.mp3 is episode 52 (the farewell). The real episode 49 was a video that went only
// to email-newsletter subscribers (it is on the Extras page) and episode 51 (Jun 25, 2008) is not in the item. EP_NUM maps file name to episode number.
const EP_NUM = { "2BB49":"50", "2BB50":"52" };
const NOTES = {
  "2BB1":"Welcome to Two Boobs and a Baby.",
  "2BB2":"Here it is… Episode 2! Today is our due date… will Sam join us?",
  "2BB3":"Introducing Sam Delaney!",
  "2BB4":"The “Holiday” Show.",
  "2BB5":"Number five is alive!",
  "2BB6":"Well, we did it. We managed to produce another podcast in the course of one week! Can you believe it? We can’t!",
  "2BB7":"Last week Heather and Sam were basking in the sun in Arizona. I was basking in the snow in New York. We’re back and Episode 7 is ready to rock!",
  "2BB8":"Sam gets his photos made, shots and his first fever – all this and more in Episode 8!",
  "2BB9":"Tonight’s episode of Two Boobs and a Baby is brought to you by the letter “T”.\n\nWhat we yammered on about:\n00:30 live from hawaii\n00:55 brought to you by the letter “t”\n02:22 pretty wild\n03:02 moving your baby to his own room\n03:19 dave don’t ball!\n03:40 getting misty over edgar\n05:28 sam’s laid back ultra sound\n06:20 things change when you have a baby\n06:33 sam laughs\n06:53 everyone gets naked at our place\n07:18 nudist colony in tennessee\n08:00 really good tip for puddy poo\n10:22 sam’s archenemies toy\n11:58 sam’s chuck t’s aren’t working yet\n13:40 dave’s disgusting things\n14:11 baby jamboree/gymboree\n15:40 swimming lesson talk\n16:43 ten, dave’s best year ever\n17:22 happy international women’s day\n19:43 diving for hockey pucks\n20:29 sam’s funny hair\n21:30 hey whitey, don’t braid your hair in jamaica\n21:42 bo derek\n22:09 mum delaney’s 70th\n22:40 sam is the life of the party\n24:15 zee and zed say hi\n24:50 adam curry plays our promo!\n25:00 canadian podcast buffet will play our promo tomorrow\n25:39 ginafish recommends keeping a baby book\n26:41 allan has exersaucer tips\n26:51 brian suggests munchkin duck bathtub\n27:05 john says hello from calgary - congrats on your latest edition!\n27:23 sign our frappr map please",
  "2BB10":"Tearing up at Pigeon Break.\n\nWhat we yammered on about:\n00:05 four sevens intro\n00:20 intro\n01:15 10pm is bed time\n02:05 st.patrick’s day review\n02:22 dave and heather dance steps\n04:10 balling for pigeon break\n05:40 tod maffin invites us to join his canadian podcast collective, foursevens network\n06:46 ten days later...sam’s in college\n07:30 sam’s big move\n08:18 drop by our forum with your suggestions\n08:45 sam’s first cereal\n11:10 lucky charms for sam\n12:45 12 hours straight\n13:48 late night debates\n16:18 dave’s call to action for toy companies...want us to test them?\n16:56 heather’s retreat\n20:45 busy week\n20:53 first day of spring, heather’s bitter\n21:52 keep your chin up, we’re canadian!\n23:00 tear free next week",
  "2BB11":"Sam’s 5th month of fun!\n\nWhat we yammered on about:\n00:30 intro\n01:00 monitor headphone tip\n01:18 sunny day in toronto\n02:10 sam and heather hitting tennessee\n02:54 walking in the beaches\n03:08 don’t taunt mother nature!\n04:25 super sam!\n05:55 rolling boy\n07:20 the two sides of heather\n07:53 pantless podcast\n10:00 you’re in yer face\n11:20 crazy penis’\n12:00 loretta bobbit? dave meant lorenna bobbit\n14:23 keep it to yo self sister\n15:24 cereal\n15:42 post your tips on our forum please\n16:25 “song of the south” by...?\n17:15 vindaloo baby food\n17:16 chips/crisps\n18:34 www.openyourears.ca\n19:09 demo-gr-atics\n19:39 andrew’s banner/userbar\n19:49 sitting on elmo\n20:42 bruce murray’s zedcast\n21:23 zee and zed are cool\n22:05 we love nova scotia\n22:15 queen of the forum “GINAFISH!”\n22:51 feeding site link\n23:40 podcasters across borders\n24:24 we also love kingston\n25:16 gauze for belly buttons\n26:20 hugs from the boy\n26:35 heading to atlanta\n27:05 dave loves chopped liver\n28:08 a surprise for episode 12...stay tuned!",
  "2BB12":"Our big surprise is revealed!",
  "2BB14":"Hear all about Sam’s six month check-up, being pregnant again, and Dave & Heather’s hot date!",
  "2BB15":"Surrounded by chaos and sleepiness… we’re back!",
  "2BB16":"Mother’s Day, Running Late, Nasty card, Designer Mums vs. Frazzled Mums, Dave’s bad back, New Toys, Pregnancy Update, French Fries, and The Sex of Baby #2!",
  "2BB17":"The A-Team, and other things…",
  "2BB18":"Find out what our new show name is.",
  "2BB19":"We’re in the June issue of Here’s How magazine! Plus: Our 5th anniversary, Dave’s getaway, Sam’s insomnia, and massages.",
  "2BB20":"Happy Canada Day! It’s Podcasters Across Borders, and more.\n\nWhat we yammered on about:\n00:20 O’Canada\n00:45 Dave’s made up “Spar” song (whatever Heather!)\n01:45 Dominion Day! (see O’Canada)\n02:06 Canada’s July 4th\n03:02 Canada’s History Quiz\n03:24 Judo (oops, it was 1882)\n04:13 Tipsy on fruit shakes\n04:57 Heather’s Allergic reaction\n05:50 Beach Idol\n06:32 PAB 2006\n07:15 Canadian Podcast Buffet\n08:05 Kingston, ON\n08:35 Dave “Obandons” Sam\n11:32 PAB - like being lost as a kid in a shopping centre\n12:00 Heather’s Day of Relaxation\n12:45 PAB Bar Meet-Up\n13:30 Thanks to Mark, Bob and Cat\n14:10 “May I have a NON-alcoholic beer please?”\n15:35 Charlie Brown “Techy Talk”\n17:33 A look into the near future for Heather\n18:30 Serenity Now!\n19:40 Trying to justify a housekeeper\n20:24 Suggestions for double stroller????\n21:26 Failed attempt at podcasting from a car with a voice recorder in a camera\n22:20 Andy from Spaceship Radio Podcast greeting\nDedicated to Finnigan. RIP.",
  "2BB21":"Sam attempts an escape from his bed, rainy day advice, fast cars and HOT women! All this and more!\n\nWhat we yammered on about:\n00:09 screaming intro\n02:39 he just doesn’t want to sleep\n03:13 just the three of us\n05:28 rain rain rain\n06:49 americanbaby.com\n11:18 dave hates dr. phil\n11:42 two boobs and a baby: the tv show\n12:07 another pantless podcast\n13:25 heather is now almost seven months preggers\n14:45 heather says “slow down”\n15:35 thank you craig and carol & neasa - you guys all rock!\n19:52 send us your comments 206-666-5362 - rainy day suggestions, cheap deals, or just to say hello!\n21:23 we buy in bulk\n22:22 please visit our forum today\n22:54 itunes feed is fixed\n23:08 frappr map shout outs\n24:15 heather and dave do the toronto grand prix\n26:15 (not) watching the world cup in little italy\n27:01 hoochie mammas\n28:00 we support you strippers",
  "2BB22":"On this show: Heather and Sam head south, Tootbrain!, Tod Maffin we hardly knew ya, stubbed toe, and more!\n\nWhat we yammered on about:\n00:35 dave jumps like a rabbit\n01:08 heather’s behind\n01:43 one hiccup? weird or not?\n02:09 “womb wall” - say it - record it - submit it!\n03:20 glucose test\n04:17 bartender bartender! tang!\n05:29 foursevens news\n05:54 tod maffin drinking game\n06:10 more about tod\n08:20 ella - big or small?\n11:15 all about laura secord\n12:02 congratualtions murna and sean!\n12:30 our big news\n12:50 sam’s future career\n14:56 advice for baby proofing please: call 206-666-5362\n17:43 craigslist.com\n19:32 heather’s baby toe\n21:40 dave has a million dollar greeting card idea\n22:22 dave heading to tennessee to join sam and heather\n22:55 frappr map shout outs\n24:47 loopy’s funny forum post\n25:24 technical difficulties from brinkster - refresh your screen if you get an error page\n26:42 have a safe trip heather, ella and sam",
  "2BB23":"Tonight: Audio comments from our friends, Sam screams and laughs, Skype call to Heather in Tennessee, all this and more!",
  "2BB24":"We're back! Tuckaleechee, Nashville, Gatorade, Ella in the bella, drunken call from Mark Blevis, audio comment from Tom, and more!",
  "2BB25":"Happy Labour Day! TV goes on, TV goes off; new apartment (kind of); adding another child guilt; and more! Things to do this week: * Call our audio comment line and say hello * Add yourself to our Frappr map * Introduce yourself on our forum * Vote for us on Podcast Alley * Help Mark Blevis if you can",
  "2BB26":"Sam gets sick, then gets us sick - the nerve of the kid eh? Audio Comment: No Credit Needed Podcast Plus: Lots of kind comments from our listeners on the blog and email. Thanks to Ross, Bruce Murray, Tom Connon, Doug Spier, and the Canadian Podcast Buffet forum folks. Call us and leave your own comments (1+206-666-5362), or click the Send Me A Voice Message link. This episode was recorded on our iRiver (Ha! Shane and Tom!) Finally... Please post your guess as to how much Ella is going to weigh. Chris D. and Noel G. were correct guessing Sam's weight of 9.3 lbs. Heather was 9.5 lb and I was 10 lb 3/4oz. Good luck!",
  "2BB27":"This episode is \"gone to pot!\" Show Notes: * Heather's back * Pregnancy update (see the countdown in the bottom of the right side of the page) * Do female babies equal harder pregnancies? * Dave's not safe at home * Scary phone * Heather's drinking problem * Used toys rule * Craig's List * Women go mad shopping! * Chudleigh's Apples * Sam's first birthday coming soon - Do you have birthday party tips for us? * Don't forget to guess Ella's weight! * Sam's birthday card coming soon...right here! * Hands, Foot and Mouth Virus * Captain Zoom * Dave loves Gordon Lightfoot- and you should too! * Child-proofing - Noel saves the day * Lovely message from Amity Promo: Just One More Book",
  "2BB28":"Here's the events leading up to Ella's debut. Thank you for all of your kind messages! We really, really, really appreciate hearing from ya'll. Cheers, Dave, Heather, Ella & Sam.",
  "2BB29":"Thanks for your patience. We're back and kicking. Sure we're sleepy...ya, of course we're buried in dirty diapers...but we've got a show to do tonight! We're back. Heather's getting smaller. Ella's a tooter! Ella joins our show. Hair talk. Heather's early escape from the hospital. PUPP sucks. Sam's first birthday. It's the Icing on the Cake, Ella says Hi (sort of). Cake pictures with Sam by Bambinos. Jo Jo leaves. Big poos. Dave's holiday. Cool bed. Tina from Germany. We're international stars! Vivian from the Clip Podcast. Ross from Dry Shave. Dawn and Drew - thanks Drew. Podcast gone to poo. A very special interview follows this show! Please don't take us seriously. Our new email address is: boobsbaby@gmail. com Cheers, Dave",
  "2BB30":"Tonight's episode includes: Nudity, Abba, Ellen, Flatulence, Sleeplessness, A broken iPod, A bloody nose, The Diaper Champ, and an apology to chickens and roosters everywhere for the sound effects confusion (gobble gobble gobble). Don't forget to call our Audio Comment line: 206-666-5362... unless you're a-fraid-y cat! Enjoy. Dave & Heather",
  "2BB31":"Tonight: Our big announcement revealed! Plus: Together again, the kids are sick in the states, Good Morning Baltimore, Alistair Christl, Sam meets Santa Claus at Riverdale Farm, and our BIG news! Don't forget to leave us your comments below. We love to hear from ya'll! Hey, and tell us where you are in the world? Click this and add your name to the map. Thanks.",
  "2BB32":"Here it is, as promised, our final podcast for 2006. It's Christmas Eve. Ella and Sam are down, Heather's fading, and I'm uploading this for you! I'll add links to the show notes to the great podcasts we mention during the show early in the new year. Or you can search for them on the Canadian Podcast Buffet (link under podcasts we love), they're all there! Tonight: Dave's unemployed, Christmas with Dave's Dad, Dave almost has his green card, screwing up Ella's schedule, Thank you to all of our listeners and fellow podcasters. Happy Holidays and New Years everyone. Have a safe and wonderful 2007! See ya'll soon. Dave & Heather",
  "2BB33":"(Almost) live from Tennessee! Tonight: Moving day; scary movers; something gets accidently stored/stolen?; PODS, great service, double check the size though; Dave has trouble at the border; Ella's smiling eyes (and stinky butt); Sleep.",
  "2BB34":"We're back. Heather is healthy, Sam's misbehaving and Ella's being as cute as a button. Tonight: Heather's been sick; baby fat; Gingivitis; thanks to Vivian and Ginafish; Heather goes crazy; What to do with a 15 month old tornado? Your advice please ; child seat video (this is very heart wrenching to watch, but it's worth seeing (and sharing) to be sure your seat is correct); good luck to the Twisted Wrist family; Oh Oh; Dave gets poo-hand; the coolest, most relaxing bedtime music for your cool kid (assuming you're cool too!). Check out www.babyrockrecords.com. We have the Zeppelin one, but I'm going to get the Ramones next for sure. Sam loves the Ramones. Don't forget to please write us a short review. Let the world know what you think of us (be nice).",
  "2BB35":"Tonight: Alternadad contest, win a copy of this awesome book by Neal Pollack; Dave & Heather party; Dave reads a book; new crib; Dr. Feel; Ella won't take a bottle (help); Mother's Day Out; snow in Tennessee; we're nominated as a finalist for a Podcast Peers Award (thanks Vivian). To enter our Alternadad Contest: - Call 206-337-1257 (or hit this link and record your message) - Leave us a message with the name of your favorite Parenting book - Don't forget to tell us your name! We'll randomly select a winner next episode. Stay tuned. Please email us if you are the winner (or if you just want to say hello): boobsbaby @ gmail.com (without the spaces). Or leave us a comment below. Good luck!",
  "2BB36":"Today is Valentine's Day, we'll celebrate another day... parenting family fun! Tonight: Alternadad Contest winner announced; croup sucks; Ella eats; Dave's trip to Montreal; Sam's first Mother's Day Out; Ella's Kung Fu, Cowboy Girl grip; Andycast's Unofficial Two Boobs biography; DryShave. Book links: \"Walter Gretzky: On Family, Hockey and Healing\"; \"Daddy Needs a Drink\"; \"Peeing in Peace\". Please leave us an audio comment 206-337-1257 about anything you'd like us to talk about. Note: Ross mentions \"pants or pantless\". This podcast was produced with pants. For more on the pant/pantless topic listen to some of our older episodes. :-) Enjoy Dave & Heather",
  "2BB37":"The last few weeks have been really hellish. We never realized how often wee ones get sick. Tonight: We offer our E-Newsletter folks a new contest (see below for details); tickle me elmo; Ella got RSV; Dave almost got killed on a rocking chair; Thanks for the get-wells everyone; US Health care Vs. Canadian Health care; Dave visits the doctor and gets naked during a cocktail; Sudafed snafu (we are not meth dealers); Dave's Dad and Gale visit; Sam learns new words; Ella rolls; Suzanne wrote to say her favorite parenting books are \"The Kid\" and \"The Commitment\" by Dan Savage; message from Shauna our Alternadad winner; message from Francis and Benjamin from Nunavut; and now.... URBAN BABY RUNWAY CONTEST DETAILS We will be selecting an E-Newsletter member by random on March 14 to win: 1 X Heart Mother T-Shirt 1 X Green Robot T-Shirt 1 X Baby Legs: Ladybug Pattern 1 X Petit Conniseur Art book 1 X Two Boobs and a Baby T-Shirt (pictured above) Good Luck!",
  "2BB38b":"38 Version 2.0 co-staring Ella! Today: Urban Baby Runway Contest WINNER!; Scarborough Dude blues and Technical boo boo with Episode 38 Version 1.0; Our second A.M. episode (Yawn free) / Dave's bright eyed and bushy tailed; Get entered for our contests by signing up for our free E-Newsletter; Delaney's clean bill of health; Girl's Night Out; Sam quits napping; Feeding tips for Ella? Your suggestions please?; Congrats to Craig and Carol our friends in Edinburgh and Katie from the Dawn and Drew family; Kids and TV; Dave's new favorite kid's show: Higglytown Heroes; Sam's first haircut; Ella's first two teeth; Wal-Mart poonami; New photos of Ella and Sam (will be posted here soon); Video Killed the Radio Star / Bob Goyetche and Andycast; Twitter.com (see Dave's Twitter below); John Kerry mentioned on C.C. Chapman; Podcasters Across Borders by Mark Blevis and Bob Goyetche; Audio Comments from our buddies Digimom and Donna downunder in Queensland Australia. Hey you..yeah you..give us a call and say hello some time. You know you want to? 206-337-1257 or record one now (see the sidebar). Cheers! Click below to say hello and see what Dave's up to: follow daveboob at http://twitter.com",
  "2BB39":"Ella hanging from Heather during dinner time. Tonight: Heather podcasts with a bugger booger (thanks Donna) on her finger; Ella's ear infection; Sam's on Spring Break; Heather gets nasty; Heather's two great ideas; Jackson Sun photographer pays a visit; Who's that knocking on the window?; Amy Sedaris, Stephen Colbert in Strangers With Candy; The Blue Jays want Dave; St. Patrick's Day - see the pictures in the E-Newsletter (sign up on the right); How we feed Ella; LISTENER EMAILS from: Aana and her links for feeding http://www.kellymom.com/bf/pumping/alternative-feeding.html and http://www.mother-2-mother.com/cups-older.htm; Donna's email about feeding with links: www.breastfeeding.asn.au, http://www.lrc.asn.au/forum/, http://www.breastfeeding.asn.au/bfinfo/biting.html; Tricia's email about Penicillin allergies; Nicole's email with Tricks to Play on Children; THANKS FOR YOUR EMAILS EVERYONE!; Please don't forget to leave a comment; More contests coming soon; Join FaceBook and say hi to Dave and (maybe) Heather; New Media Nashville; Ella cracks us up!",
  "2BB40":"We start the show in Perkins over breakfast; continue from Wal-Mart's parking lot; Rachel's wedding, Dave liberates the drinkers; Jackson Sun article April 17th (we'll have a link here); Dave's birthday is April 16th!; Stacey Baker new photos of Ella and Sam; April Fool's Day; Triplet's birthday; Ella's got teeth (and she ain't afraid to use them); parenting is all about poo; Sam's secret wrestling move (watch yer heads!); Easter eggs faux paux; Trick or Treating time; Dave's knowledge of horror movies ruins a popular children's song; forum is down for now, stay tune for it's resurrection soon; a word from Sam. The ASHLEY'S BIG SECRET CONTEST: Question: WHAT IS THE MOST USEFUL ITEM that you used in your child's first year? Leave us an audio comment - 206-337-1257 - and be sure you're registered in our E-Newsletter to enter (registration is free of course). You can also answer the question by leaving a comment here if you prefer. Prizing includes (subject to availability): Hammered Silver Cuff Leopard Rectangle Earrings Black Silky Bead Set Hammered Silver Band Ring Brown Barrel SetLong Red and Turquoise Bead Set",
  "2BB41":"Today: Live from the parking lot of the Cajun Cooker @ the Olde English Inn; special package from Tim @ The Twisted Wrist Podcast; Joan's \"60th\" birthday; Dave's 35th birthday hot date; Heather's birthday is May 8th (thanks Ginafish!); Heather's third sober birthday; Jackson Sun article, C.C. Chapman notes a minor misquote; we're house shopping; Ella screaming in the car; Sam's mind is blown at the hotel; Ella has her first swim; Jack's 2nd birthday; Sam loves the sand table; Thomas the Train set; www.craigslist.com; Ella is sitting up and rolling; Ella moved out; Sam jams out with the booming beats in the park; honk honk!; Sam plugs his ears; Emails; Ashley's Big Secret Contest winner is...plus the list of your choices for most useful items (coming soon) in your child's first year. Dave's new favourite item is the DadGear vest - check it out here. Please don't forget to leave us your comments below. We love hearing from you!",
  "2BB42":"Tonight: Happy Mother's Day; Nashville is Talking; big news; Dave is moving to Nashville four nights a week; we use the word \"crazy\" too often; podcasting once a week is proving difficult; Ella's taking bottles (woo hoo!); Lindsay suggests the boob bottle nipple; please tell us your tips for aching boobs; call us 206 350 4819; Momo's visit; trip to the zoo; Ella does the monkey call; Heather's 32nd birthday; is Heather the only podcaster without a MP3 player?; Dave buys a fake ipod on Ebay; name that ice cream cone?; Heather's road trip advice for traveling with a baby; Sam rides a pony at the Humbolt Strawberry Festival; Magnet School House; Dave's awkward massage; we're looking for a train table; happy 6th to Ross and Karen from DryShave; congratulations to Steve and Maureen from the Wicked Good Podcast; happy 100th episode to the Scarborough Dude from Dicks n' Janes; congrats to Gregg & Eileen; look us up on Facebook; Rob from the UK confirms the British need for booze, the return of pantless podcasts is near...",
  "2BB43":"Join Dave and Heather as they car cast episode 43 of Two Boobs and a Baby +; 800 things a day; Podcasters Across Borders; dedicated to Ella Bean; \"I want juice\"; Dave loves his job; terrible twos; our house; Scarface poster; Heather gets attacked (by a bird); more barbecue than you can shake a hog's tail @; lactating-free since May 2007; car titles, you should keep them; Father's Day Contest: Daddy Needs a Drink by Robert Wilder; Heather advocates drug use by mothers (not really, it's a joke); Heather's new poonami story (possibly the mother of all poonamis); BarCamp Nashville; audio comment from Ginafish - we love you Ginafish! Father's Day Contest To enter: Send us an audio comment by calling: 206-350-4819 or record it for free here. Tell us why your daddy deserves a copy of Daddy Needs a Drink. Don't forget you need to be a member of our free E-Newlsetter, sign-up in the red box along the right side of the page. Good luck! We'll be drawing Sunday, June 10. Thanks for listening. Stay subscribed. Cheers, Dave & Heather",
  "2BB44":"We're back. Thanks for staying subscribed. Today we catch up and announce the winners of our \"Daddy Needs a Drink\" contest, sorry about the delay folks. Plus, we catch up on our new house, Ella and Sam updates, BarCamp Nashville, Shane and Tom, and much more. It's nice to back. Please comment on the show by calling 206-350-4819 or email us at boobsbaby AT gmail DOT com.",
  "2BB45":"Stuff in your teeth, ad words = microphone, sitting in the screened-in porch, visit home to Toronto, sleeping with the kids, Ella's first birthday is October 9, Sam's second birthday is October 25, Mickey Mouse Club, Sam's pacifier addiction, call us 206-350-4819, Gnomedex, BarCamp Nashville, PodCamp Nashville, meetup.com, Heather got pooped on, find Dave on Twitter: www.twitter.com/davedelaney, bath tub poo tips, Caddyshack, Podcast New Media Expo, Emma, They Might Be Giants, Higglytown Heroes, kids cool rock n' roll bands? Would you like to include your music in our show? We'd love to feature some cool new music for kids. Let us know. UPDATE: If I was unclear I apologize. Please only click the ads if you're interested in the products. I did mention that clicking ads helps us pay for the show, but it's important to understand that I'm not plugging that you go click crazy. If you see an ad that interests you please DO click it to check it out. Thanks. Dave.",
  "2BB46":"A long over due episode during Dave's morning commute. Link love in Episode 46 includes: PodCamp Nashville, Emma Email Marketing, New Media Expo, monetization. Find Dave at his new blog: www.davemadethat.com and on Twitter: www.twitter.com/davedelaney. Audio Comments from: Charles Cadenhead and Vivian, Andy and T.J. Thanks guys. Thanks to everybody else who left us comments recently to wish us a happy second year podcasting, happy first birthday Ella, and happy second birthday Sam. Our listeners all rock!",
  "2BB47":"Warning: This episode may ruin Christmas. Do not listen with your wee ones. Show notes: - We're back and we're almost at 50 episodes. Congrats to Joe @ JaffeJuice for 100 episodes - Update about the kids. Ella is now 15 months and Sam is 26 months - Kissing TVs - Who's more southern sounding? - Christmas recap: gobble gobble - New friends in the neighborhood - Dogs pooping in our yard - RSS explained by Heather - The stomach virus from hell - Yo Gabba Gabba - Heather's \"relaxing\" weekend away - Sleep deprived - Please call us 206-350-4819 and leave an audio comment - PodCamp Nashville - Find Dave on Twitter: www.twitter.com/davedelaney - Join our Facebook Group",
  "2BB48":"first episode in eight weeks, or two months - Sam is almost 2 1/2 and Ella is 17 months old - letting the little ones cry it out - Ella is talking up a storm - Heather's theme song for Ella (sorry Queen) - Sam's becoming a cool big brother - PodCamp Nashville - PodCamp Toronto - SXSW Interactive (read about it on Dave's blog) - Dave missed the Nashville snow - Easter egg hunting on the farm - tickled by a rooster - Did you get photos with the Easter bunny? Please comment and tell us - Easter egg hunting continues at the Nashville Zoo (which rocks by the way)",
  "2BB49":"Show notes: - Thanks to Tommy Vallier for saving our blog. Read about that here. - Dave comes on to the mom listeners - Father's Day recap - 9 am cookies - Ella's first day at school (Mother's Day Out) - Switching from bottles to cups - Monkey see, monkey do. How Sam is copying kids and Ella is copying our bad habits - Dave's Slip N' Slide mishap (Video) - Spiders are trying to kill Dave - Ella and Sam are swimming - Heather's swimming tip - Dave hates Dora & Barney - We love Yo Gabba Gabba - Ella is obsessed with Mickey Mouse (AKA \"Hotdog\")"
};

const epList = document.getElementById("ep-list");
const epCount = document.getElementById("ep-count");
const players = [];

const formatTime = s => {
  s = parseFloat(s);
  if (!s || isNaN(s)) return "--:--";
  return Math.floor(s / 60) + ":" + String(Math.floor(s % 60)).padStart(2, "0");
};
const esc = s => String(s).replace(/&/g, "&amp;").replace(/</g, "&lt;").replace(/"/g, "&quot;");

fetch(`https://archive.org/metadata/${ARCHIVE_ITEM}`)
  .then(r => r.json())
  .then(data => {
    const mp3s = data.files.filter(f => f.name.toLowerCase().endsWith(".mp3"));
    mp3s.sort((a, b) => a.name.localeCompare(b.name, undefined, { numeric: true, sensitivity: "base" }));

    epCount.textContent = `${mp3s.length} episodes in the vault`;

    epList.innerHTML = mp3s.map(file => {
      const raw = file.name.replace(/\.[^/.]+$/, "");
      const isBonus = /bonus/i.test(raw);
      const num = isBonus ? "Bonus" : (EP_NUM[raw] || raw.replace(/^2BB/i, ""));
      const title = file.title || raw;
      const url = `https://archive.org/download/${ARCHIVE_ITEM}/${encodeURIComponent(file.name)}`;
      return `
        <div class="ep">
          <div class="ep-grid">
            <span class="ep-play"><audio class="plyr-player" preload="none" controls><source src="${url}" type="audio/mpeg"></audio></span>
            <span class="code">${isBonus ? "BONUS" : "2BB-" + esc(num)}</span>
            <span class="year">${DATES[raw] || YEARS[raw] || "—"}</span>
            <span class="title" title="${esc(title)}">${esc(title)}</span>
            <span class="dur">${formatTime(file.length)}</span>
            ${!NOTES[raw] ? "" : NOTES[raw].length > 200
              ? `<details class="ep-notes"><summary>Show notes</summary>${esc(NOTES[raw])}</details>`
              : `<span class="ep-notes">${esc(NOTES[raw])}</span>`}
          </div>
        </div>`;
    }).join("");

    epList.querySelectorAll(".plyr-player").forEach(el => {
      const row = el.closest(".ep");
      if (typeof Plyr === "undefined") { players.push(el); return; } // native <audio> fallback
      const p = new Plyr(el, {
        controls: ["play", "progress", "current-time"],
        iconUrl: "https://cdn.plyr.io/3.7.8/plyr.svg",
        invertTime: false
      });
      p.on("play", () => {
        players.forEach(o => o !== p && o.pause());
        epList.querySelectorAll(".ep.current").forEach(r => r.classList.remove("current"));
        row.classList.add("current");
      });
      players.push(p);
    });
  })
  .catch(err => {
    console.error("Failed to load archive metadata:", err);
    epCount.textContent = "Archive unavailable";
    epList.innerHTML = `<div class="ep-loading">Couldn't reach the Internet Archive. Try again in a bit — or <a href="https://archive.org/details/${ARCHIVE_ITEM}" target="_blank" rel="noopener">listen on archive.org</a>.</div>`;
  });
